# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: GetClanAreaLeaderboardInfo.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'GetClanAreaLeaderboardInfo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n GetClanAreaLeaderboardInfo.proto\x12\x05proto\"L\n\x1aGetClanAreaLeaderboardInfo\x12\x0f\n\x07\x63lan_id\x18\x01 \x01(\x05\x12\x1d\n\x07\x65ntries\x18\x04 \x03(\x0b\x32\x0c.proto.Entry\"J\n\x05\x45ntry\x12\x0f\n\x07\x61rea_id\x18\x01 \x01(\x05\x12\x30\n\x10leaderboard_info\x18\x02 \x01(\x0b\x32\x16.proto.LeaderboardInfo\"E\n\x0fLeaderboardInfo\x12\x0c\n\x04rank\x18\x01 \x01(\x05\x12\x16\n\ttimestamp\x18\x02 \x01(\x03H\x00\x88\x01\x01\x42\x0c\n\n_timestampb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GetClanAreaLeaderboardInfo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETCLANAREALEADERBOARDINFO']._serialized_start=43
  _globals['_GETCLANAREALEADERBOARDINFO']._serialized_end=119
  _globals['_ENTRY']._serialized_start=121
  _globals['_ENTRY']._serialized_end=195
  _globals['_LEADERBOARDINFO']._serialized_start=197
  _globals['_LEADERBOARDINFO']._serialized_end=266
# @@protoc_insertion_point(module_scope)
